server:
  port: 7000
spring:
  application:
    name: shop-gateway
  zipkin:
    base-url: http://192.168.7.1:9411/ #server请求地址
    discovery-client-enabled: false # 让nacos把它当成一个url 不当做服务
    sleuth:
      sampler:
        probability: 1.0 #采样百分比
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.7.1
    gateway:
      discovery:
        locator:
          enabled: true #允许gateway从nacos发现微服务
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: product_route
          uri: lb://shop-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
            - Log=false,true  #局部过滤器
        - id: order_route
          #127.0.1.1:7000/api/order/message0 lb://shop-order/order/message0
          uri: lb://shop-order
          predicates:
            - Path=/api/order/**,/api/seata/**
          filters:
            - StripPrefix=1
            - Log=true,false  #局部过滤器
    sentinel:
      transport:
        dashboard: 192.168.7.1:9090 #控制台服务地址
        port: 8721  #跟控制台交流的端口 随意指定未使用的即可
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true